disabled_rules:
  - standard:function-naming
  - standard:no-wildcard-imports
  - standard:import-ordering
  - standard:annotation
  - standard:wrapping
  - standard:parameter-list-wrapping

experimental:
  enabled: false

android: true

reporters:
  - plain
  - checkstyle
